application: gustavoliveiradev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/images

- url: /client
  static_files: static/views/indexClient.html
  upload: static/views/indexClient.html

- url: /dessert
  static_files: static/views/dessertView/indexDessert.html
  upload: static/views/dessertView/indexDessert.html

- url: /addDessert
  static_files: static/views/dessertView/includes/addDessertView.html
  upload: static/views/dessertView/includes/addDessertView.html

- url: /ingredient
  static_files: static/views/ingredientView/mainIngredient.html
  upload: static/views/ingredientView/mainIngredient.html

- url: /request
  static_files: static/views/requestView/mainRequest.html
  upload: static/views/requestView/mainRequest.html

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.html)$
  static_files: static/\1
  upload: static/.*\.html$

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
