application: gustavoliveiradev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /js
  static_dir: static/js

- url: /client
  static_files: static/indexClient.html
  upload: static/indexClient.html

- url: /
  static_files: static/indexDessert.html
  upload: static/indexDessert.html

- url: /(.*\.html)$
  static_files: static/\1
  upload: static/.*\.html$

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
